version: "3.8"

services:
  db:
    image: postgres:15.3 
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/up.sql:/docker-entrypoint-initdb.d/init.sql
  golang:
    build: .
    env_file:
      - .env
    ports:
      - 80:80